version: '3'
services:
  client:
    build: ./client
    ports:
      - '80:80'
    depends_on:
      - api
  api:
    build: ./api
    ports:
      - '5000:5000'
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
